version: 2
updates:      
  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"