# An action to push templates to coder server

name: MATLAB

on:
  push:
    branches:
      - main
    paths:
      - "matlab/main.tf"
      - ".github/workflows/matlab.yaml"
  workflow_dispatch:

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest short commit SHA
        id: get_commit_sha
        run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: update coder template
        uses: matifali/update-coder-template@v3
        with:
          url: ${{ vars.CODER_URL }}
          id: "matlab"
          dir: "matlab"
          name: ${{ steps.get_commit_sha.outputs.sha_short }}
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
